### ISSUE TITLE
4PriorContradictoryJuliaCaesarStable Binder Notebook (Content Draft)

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/BinderNotebooks#4]
Populate with content: https://github.com/NavAbility/BinderNotebooks/blob/main/julia/caesar-api/icra-4-contradictorydata.ipynb

**Comment by dehann** [comment]
Going to keep this in Prime Path status for now, since we are not working on this at the moment.  Focussing on getting 1-3 done before end March.

**Comment by dehann** [comment]
I would like @Affie to please help generate the content for this Tutorial 4, based on experience from RA-L paper and construction example.  I wrote the outline sketch, so that is ready and waiting.

**Comment by dehann** [comment]
Hi @Affie , I'm going between a whole bunch of things at the moment.  Could you please work this issue this week -- at minimum make sure the API / SDK calls that we need are working end to end please.

If you can also noodle further our idea of the robot arm + laser range finder calibration (hand eye calibration) with nav affodances?  

----

We can call again during the week if you are stuck, but this ticket must progress without blocking on me please.  The main things we want to show are
- contradictory data 
- nav affordances
- Robotics that is not a wheeled robot.
- Calibration something, 

xref:
- https://github.com/NavAbility/ICRA2022/issues/43

**Comment by dehann** [comment]
I'm taking over from Johan on this for now.

**Comment by dehann** [comment]
Johan's tut4 is a really good example, and worth some numerical performance improvements to make it run smooth.  

As I'm looking at it more, the numerical thing to improve is the implicit null hypo case that occurs during the multihypo processing (for a relative factor).

In the Tut4 example, there are 4 landmarks with priors.  That solves easy.  Add first pose with multihypo to all four landmarks, and that too is easy for the solver to find.  

Step three shows numerical variation when odo x0 --> x1 is added and solved.  The correct result is two hypotheses are stable in solves for poses (x0,x1).  The current solve performance regularly finds both modes and maintains them during multiple solves.  Sometimes though, only one mode is recovered by the solver -- from there repeat solves currently do not rejuvenate the second mode, even though they are clearly present in the proposal distributions.

This is all in one clique, here is the clique graph bi-adjacency:
![Screenshot from 2022-04-23 08-51-28](https://user-images.githubusercontent.com/6412556/164913685-b767558f-7a04-42e4-9565-ffa406537263.png)

The hold up is the two multihypo factors from each of the two poses are not allowing the alternate mode in to the solution easy enough.  This is supposed to happen with the implicit null fraction:
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/61f90af05137bf87e820e1c36485781ffd308cec/src/ExplicitDiscreteMarginalizations.jl#L170-L175

I'm going to dig into these numerics a little here, since this is a small and really good test case and worth improving.

**Comment by dehann** [comment]
Ah, Johan, think I know what's going on with the modes being lost on solve after :x1.  The odo relative needs to have implicit null hypo, owing to the fact that it my have incorrect numerics based on the initial condition.  So I'm considering that sort of fix.  This discussion actually fits better as issue on IIF.  I'll move it over there with clearer description of the update.

**Comment by dehann** [comment]
This should over come the variation in solves Johan was taking about (actually was a shortcoming that's been in the code for a long time):
- https://github.com/JuliaRobotics/IncrementalInference.jl/pull/1518

**Comment by GearsAD** [comment]
Lol 2/3rds of this is proto-indo-European but I get that modes are lost. From what I get, it seems we just need to give more info (the nullhypo) via the API to resolve it?
